name: py37cmp-gui

channels:
- aramislab
- anaconda
- conda-forge
- conda-forge/label/cf201901
- defaults

dependencies:
- python=3.7
- pip=20.1.1
- numpy=1.18.5
- matplotlib=3.2.2
- traits=6.0.0
- traitsui=6.1.3
- graphviz=2.40.1
- nipype=1.5.0
- git-annex=8.20210127
- pyside2=5.9.0a1
- fslpy=3.2.1
- fsleyes=0.33.0
- indexed_gzip=1.2.*

- pip:
    - duecredit==0.8.0
    - dipy==1.1.1
    - mne==0.20.7
    - obspy==1.2.1
    - datalad[full]==0.14.0
    - datalad-container==1.1.2
    - datalad-neuroimaging==0.3.1
    - datalad-osf==0.2.3.1
    - pybids==0.10.2
    - apptools==4.5.0
    - statsmodels==0.11.1
    - networkx==2.2
    - sphinx==3.1.1
    - sphinx_rtd_theme==0.5.0
    - sphinx-argparse==0.2.5
    - recommonmark==0.6.0
    - pydicom==2.0.0
